# Prefix binding {{{
unbind C-b
set-option -g prefix C-Space
bind-key Space send-prefix
bind-key C-Space last-window
# }}}

# General {{{
set -sg escape-time 0
setw -g aggressive-resize on
bind R source-file ~/.tmux.conf
bind x confirm-before -p "kill-window #W? (y/n)" kill-window
set -g default-terminal "screen-256color"
set-option -g default-shell /bin/bash
set -g mouse on
set -g history-limit 9999999
# }}}

# Set window notifications {{{
setw -g monitor-activity on
set -g visual-activity on
# }}}

# Automatically set window title
setw -g automatic-rename
# }}}

# window management {{{
unbind %
unbind s
bind | split-window -h
bind _ split-window -v
bind-key S command-prompt "attach-session -t '%%'"
bind-key s choose-session
bind Z if -F '#{@layout_save}' \
    {run 'tmux select-layout "#{@layout_save}" ; set -up @layout_save'} \
    {set -Fp @layout_save "#{window_layout}" ; run 'tmux resize-pane -y 100%'}
# }}}

# {{{ pane management
set-window-option -g mode-keys vi
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
# }}}

# https://gist.github.com/admackin/4507371
# # fix ssh agent when tmux is detached
# # See .ssh/rc for socket linking
set -g update-environment -r
setenv -g SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock
#set -g update-environment "DISPLAY SSH_ASKPASS SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY"
#set-environment -g SSH_AUTH_SOCK $HOME/.screen/ssh-auth-sock-$USER


# Snazzy Theme for tmux

# default statusbar colors
set-option -g status-style bg=colour0,fg=colour205

# default window title colors
set-window-option -g window-status-style fg=colour123,bg=default,dim

# active window title colors
set-window-option -g window-status-current-style fg=colour84,bg=default,bright
setw -g window-status-current-format '● #[default,noreverse]#W '

# pane border
set-option -g pane-border-style fg=colour81
set-option -g pane-active-border-style fg=colour84

# message text
set-option -g message-style bg=colour81,fg=colour17

# pane number display
set-option -g display-panes-active-colour colour203
set-option -g display-panes-colour colour84

# clock
set-window-option -g clock-mode-colour colour205

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize tmux plugin manager (keep these lines at the bottom of tmux.conf)
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
run '~/.tmux/plugins/tpm/tpm'
