#!/bin/sh
rm -f $(git rev-parse --git-dir)/tags
git ls-files | xargs -d\\n ctags --tag-relative=yes -f $(git rev-parse --git-dir)/tags --languages=-javascript,sql --python-kinds=-i

# ctags for a js project with gjsctags:
# https://github.com/AnyChart/gjstags
# git ls-files | grep "\.js$" | xargs -d\\n gjstags -f $(git rev-parse --git-dir)/tags && sed -i "s/\t/&..\//" $(git rev-parse --git-dir)/tags
